image: Visual Studio 2017
install:
  - cinst fake
configuration: Release
init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd -t Bundle
test: off
version: 0.0.1.{build}
artifacts:
  - path: artifacts
    name: artifacts